### ISSUE TITLE
Creating $assetsDirectory fails silently if the system user has no permissions to create directories

### ISSUE THREAD

**Issue by Taitava** [frontpack/composer-assets-plugin#10]
Hi,

if you take a look at the `AssetsInstaller.php` file, you will find the following:
Line 56 calls a method:
```php
$this->createDirectory($assetsDirectory);
```

And the method is defined in the same file on lines 383 - 386:
```php
private function createDirectory($directory)
{
	@mkdir($directory, 0777, TRUE);
}
```

The program will not notice that it was not able to create the directory, because errors are suppressed by the `@` symbol and createDirectory() does not test whether the new directory exists after trying to create it.

I think this could be better handled by throwing an `Exception`:
```php
private function createDirectory($directory)
{
	$succeeded = @mkdir($directory, 0777, TRUE); // Keep the @ symbol to prevent E_WARNING's from being emitted.
	if (!$succeeded) throw new FailedToCreateDirectoryException($directory);
}
```

```php
class FailedToCreateDirectoryException extends Exception {};
```

Now the thrown exception can be left uncaught and it will terminate the program execution and clearly tell what went wrong.

**Comment by janpecha** [comment]
Fixed, thanks for report!
