### ISSUE TITLE
Composer 2 support

### ISSUE THREAD

**Issue by MartyThornley** [frontpack/composer-assets-plugin#11]
Hi,

I have been testing for Composer 2, which requires composer-plugin-api version 2. composer-assets-plugin currently requires ^1.0.0. Any plans to update to Composer 2 compatibility? 

Thanks. 

Details: https://php.watch/articles/composer-2#plugin-api-2

**Comment by janpecha** [comment]
Hello, I just added support for Composer 2 to `dev-master`. Please test it.

**Comment by janpecha** [comment]
Released as version `0.11.0`.
