### ISSUE TITLE
Copy still creats simlinks on macOS

### ISSUE THREAD

**Issue by JE4GLE** [frontpack/composer-assets-plugin#13]
Hello,

My main project (A) has the following options:
`"extra": {
    "assets-files": "assets",
    "assets-dir": "libraries",
    "assets-strategy": "copy"
  },`

Now I want to include the project A into another project (B) and copy the assets files. When updating the composer package, the composer-assets-plugin does not copy the asset files, but creates simlinks.

Did I configure anything wrong?

**Comment by janpecha** [comment]
Hello,

you must add `"extra": { "assets-dir": "libraries", "assets-strategy": "copy" }` into project (B). Options `assets-dir` & `assets-strategy` are read only from root `composer.json`.

Project (A):

```
"extra": { "assets-files": "assets" }
```

Project (B):

```
"extra": { "assets-dir": "libraries", "assets-strategy": "copy" }
```

**Comment by JE4GLE** [comment]
Thanks! Ticket can be closed, but maybe see it as a suggestion to include a better documentation ^^
