### ISSUE TITLE
Option 'assets-target' (root package)

### ISSUE THREAD

**Issue by janpecha** [frontpack/composer-assets-plugin#3]
For tinymce,....

```
"config": {
    "assets-target": {
        "org/package": "path/to/directory",
        "org/package2": "path/to/directory2"
    }
}
```

**Warning:** can be destructive

**Comment by pavarnos** [comment]
that looks just like what i need... a way to map package names to friendlier directories

to make it safe (non destructive) you could
- throw an exception if it is outside "assets-dir"
- allow "assets-dir" to be an array of allowed / safe directories

**Comment by janpecha** [comment]
Hi, thanks for hints, I added this feature just now.

> throw an exception if it is outside "assets-dir"

Purpose of `assets-target` is have option to specify directory for package outside of `assets-dir`. Specified directory cannot be inside `assets-dir`, because `assets-dir` have strict structure and `assets-target` can damage this structure.

> allow "assets-dir" to be an array of allowed / safe directories

Array of "allowed" directories is specified by user in `assets-target`, array in `assets-dir` is unnecessary.

---

EDIT: Of course you can use it to map packages to own structure, for example:

```
"config": {
	"assets-dir": "_assets",
	"assets-target": {
		"org1/package1": "assets/package1",
		"org2/package1": "assets/package2"
	}
}
```
